
debug: false

spring:
  h2:
    console:
      enabled: true
      path: /h2-console




  datasource:
    initialize: true
    url: jdbc:h2:mem:nkdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true

