INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME) VALUES (1, 'TEST1');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME) VALUES (2, 'TEST2');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME) VALUES (3, 'TEST3');

INSERT INTO ROLE (ROLE_ID, ROLE_TYPE) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ROLE_ID, ROLE_TYPE) VALUES (2, 'USER');

INSERT INTO ACCOUNT_ROLE (ID, ACCOUNT_ID, ROLE_ID) VALUES (1, 1, 1);
INSERT INTO ACCOUNT_ROLE (ID, ACCOUNT_ID, ROLE_ID) VALUES (2, 1, 2);
INSERT INTO ACCOUNT_ROLE (ID, ACCOUNT_ID, ROLE_ID) VALUES (3, 2, 2);
INSERT INTO ACCOUNT_ROLE (ID, ACCOUNT_ID, ROLE_ID) VALUES (4, 3, 2);
