INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME) VALUES (1, 'TEST1');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME) VALUES (2, 'TEST2');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME) VALUES (3, 'TEST3');