CREATE TABLE ACCOUNT
(
    ACCOUNT_ID INT NOT NULL,
    ACCOUNT_NAME VARCHAR(50) NOT NULL,
    CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHANGED1 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE NAMKYU_USER
(
    SEQUENCE_ID BIGINT AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
);