CREATE TABLE ACCOUNT
(
    ACCOUNT_ID INT NOT NULL,
    ACCOUNT_NAME VARCHAR(50) NOT NULL,
    CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHANGED1 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE NAMKYU_USER
(
    SEQUENCE_ID BIGINT AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
);


CREATE TABLE MEMBER_STUDY (
    ID VARCHAR(255) NOT NULL, --아이디(기본 키)
    NAME VARCHAR(255),        --이름
    AGE INTEGER NOT NULL,     --나이
    PRIMARY KEY (ID)
)